### ISSUE TITLE
关于使用特征可视化的，请问一下我可以看每层的总输出吗？而不是各个维度的

### ISSUE THREAD

**Issue by ASguoyue** [positive666/yolov5_research#10]

**Comment by ASguoyue** [comment]
类似使用grad—cam这样的可视化

**Comment by positive666** [comment]
> 

你说的是feature map上的热力图可视化啊 这个没有实现啊

**Comment by positive666** [comment]
> 类似使用grad—cam这样的可视化

参考下yolo.py的 可以手动调用visual

**Comment by ASguoyue** [comment]
> > 
> 
> 你说的是feature map上的热力图可视化啊 这个没有实现啊
是的是使用热力图的形式

**Comment by ASguoyue** [comment]
> > 类似使用grad—cam这样的可视化
> 
> 参考下yolo.py的 可以手动调用visual

好的已经采用了visual的方法进行了测试
