### ISSUE TITLE
yolo.py运行yolov5-transformer.yaml报错

### ISSUE THREAD

**Issue by Someone1Wu** [positive666/yolov5_research#11]
作者大大，我从您的model/hub 文件和yolov5原作者的代码里现在mater版本的model/hub里加载yolov5-transformer.yaml，运行yolo.py都出现了报错：TypeError: new(): argument 'size' must be tuple of ints, but found element of type float at pos 2，这是什么原因呀？

**Comment by positive666** [comment]
类型错了估计是  那个是作者的 我没用过  也许修复了tuple类型

**Comment by Someone1Wu** [comment]
> 类型错了估计是 那个是作者的 我没用过 也许修复了tuple类型

大大，在你那里加载transformer.yaml运行yolo.py也会报错吗？这应该怎么改嘞？

**Comment by Someone1Wu** [comment]
> 
大大，下什么接口呀，不是很明白

**Comment by xxxjjjx** [comment]
请问你姐解决这个问题了吗

**Comment by Someone1Wu** [comment]
> 解决了

兄弟，你是怎么解决的呀，可以交流一下吗？
