### ISSUE TITLE
BoT

### ISSUE THREAD

**Issue by Sa-UpWorld** [positive666/yolov5_research#12]
## ❔Question

感觉BoT好像不如C3块和C3TR块，可以减少参数量但会拉低一部分精度啊

**Comment by positive666** [comment]
> ## ❔Question
> 感觉BoT好像不如C3块和C3TR块，可以减少参数量但会拉低一部分精度啊
> 
> ## Additional context

GAM还可以 你试试 BOT最近没管了 想趁业余时间把SWINV2.0 完善了 不然过一阵子官方都开源了

**Comment by Sa-UpWorld** [comment]
> > ## ❔Question
> > 感觉BoT好像不如C3块和C3TR块，可以减少参数量但会拉低一部分精度啊
> > ## Additional context
> 
> GAM还可以 你试试 BOT最近没管了 想趁业余时间把SWINV2.0 完善了 不然过一阵子官方都开源了

您好，我观察到GAM计算量很大，请问有哪些策略可以降低其复杂性呢，我用了4个GAM增加了20GFLOPs

**Comment by positive666** [comment]
> > > ## ❔Question
> > > 感觉BoT好像不如C3块和C3TR块，可以减少参数量但会拉低一部分精度啊
> > > ## Additional context
> > 
> > 
> > GAM还可以 你试试 BOT最近没管了 想趁业余时间把SWINV2.0 完善了 不然过一阵子官方都开源了
> 
> 您好，我观察到GAM计算量很大，请问有哪些策略可以降低其复杂性呢，我用了4个GAM增加了20GFLOPs

正在改 用dwconv 但是测试好像有点问题
