### ISSUE TITLE
SWIN

### ISSUE THREAD

**Issue by PeterSmith1** [positive666/yolov5_research#13]

**Comment by positive666** [comment]
> ## ❔Question
> ## Additional context您好，我想问一下，如果SWIN V2不好训练的话，您有采用拿SWIN 1.0版去修改吗？

我目前是只插某几层训练 后面有时间会研究下更新下swinv2的代码，也可以等着开源，比如我随意在Virsdone数据集上 插了三层SWINV2 三层GAM，提了1.3个点，我最近抽卡要学学理论 再来改这个代码哈
