### ISSUE TITLE
Doecoupled Head

### ISSUE THREAD

**Issue by yyy8439** [positive666/yolov5_research#14]
## ❔Question

可以具体讲一下代码里解耦头具体的方法过程吗
## Additional context
很清楚啊 就是在head部分加两个分支的卷积组 一个分支：分类 ，另一个分支：回归和前景置信度 然后在CAT回去 就可以了 类似于YOLOX，里面可以作卷积核微调 因为FLOPs明显增大了  后续会在CSDN上作详细说明

**Comment by Sa-UpWorld** [comment]
请问作者，Doecoupled 对提点有帮助吗，检测头解耦了AP应该会降低吧

**Comment by positive666** [comment]
> 请问作者，Doecoupled 对提点有帮助吗，检测头解耦了AP应该会降低吧

你好 解耦就是为了提高性能的 缓解分类和回归的不一致性 需要对HEAD从新训练

**Comment by Sa-UpWorld** [comment]
> > 请问作者，Doecoupled 对提点有帮助吗，检测头解耦了AP应该会降低吧
> 
> 你好 解耦就是为了提高性能的 缓解分类和回归的不一致性 需要对HEAD从新训练

您好,感谢您的回复,如果我的Backbone与Neck已训练好后,要如何训练解耦头呢,是加了解耦头先训练一次,在利用训练出的best继续训练吗

**Comment by positive666** [comment]
> 

可以直接训练 不过要200+的epoch 还有就是你可以冻结前面的固定层加速下 训练

**Comment by positive666** [comment]
有反馈说这个线上的版本 解耦头不收敛 我考虑还原我本地的代码 不过现在还需确认下是这个版本的代码问题与否
