### ISSUE TITLE
关于自己的数据训练问题汇总

### ISSUE THREAD

**Issue by ASguoyue** [positive666/yolov5_research#20]
问题反馈：无法加载自己数据文件txt，无法生成.cache文件，在dataset.py中，第512行
![image](https://user-images.githubusercontent.com/43775884/163308385-e7a92f67-d51e-47ba-8ecc-754e18f63d93.png)

解决方法：要把img_files改为im_files即可

**Comment by positive666** [comment]
> 问题反馈：无法加载自己数据文件txt，无法生成.cache文件，在dataset.py中，第512行 ![image](https://user-images.githubusercontent.com/43775884/163308385-e7a92f67-d51e-47ba-8ecc-754e18f63d93.png)
> 
> 解决方法：要把img_files改为im_files即可

整个代码更新过很多次了  你应该没有用新的代码
