### ISSUE TITLE
yolov5s_swinv2_head.yaml配置运行报错

### ISSUE THREAD

**Issue by zqyJason** [positive666/yolov5_research#21]
## ❔Question
请问完全按照项目文件设置，在自己的数据集上，使用`yolov5s_swinv2_head.yaml`文件，总是显示以下错误：
`RuntimeError: Given groups=1, weight of size [1024, 128, 1, 1], expected input[1, 32, 32, 128] to have 128 channels, but got 32 channels instead`
没有自己改动，貌似是输入维度不匹配问题，但是找不到根源在哪，求教。

**Comment by wch243294382** [comment]
AutoAnchor: 5.36 anchors/target, 1.000 Best Possible Recall (BPR). Current anchors are a good fit to dataset ✅
Traceback (most recent call last):
  File "train.py", line 678, in <module>
    main(opt)
  File "train.py", line 575, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 305, in train
    compute_loss = ComputeLoss(model)  # init loss class
  File "/home/wch/yolov5_research/utils/loss.py", line 107, in __init__
    self.g2=h['fl_eiou_gamma'] # focal eiou loss gamma
KeyError: 'fl_eiou_gamma'
我是出这个问题- - 也不知道咋回事

**Comment by lyj107** [comment]
Traceback (most recent call last):
  File "train.py", line 676, in <module>
    main(opt)
  File "train.py", line 573, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 107, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "/root/yolov5_research-master/utils/general.py", line 493, in check_dataset
    check_font('Arial.ttf' if is_ascii(data['names']) else 'Arial.Unicode.ttf', progress=True)  # download fonts
TypeError: check_font() got an unexpected keyword argument 'progress'
我是这个问题

**Comment by shenshi19** [comment]
> Traceback (most recent call last): File "train.py", line 676, in main(opt) File "train.py", line 573, in main train(opt.hyp, opt, device, callbacks) File "train.py", line 107, in train data_dict = data_dict or check_dataset(data) # check if None File "/root/yolov5_research-master/utils/general.py", line 493, in check_dataset check_font('Arial.ttf' if is_ascii(data['names']) else 'Arial.Unicode.ttf', progress=True) # download fonts TypeError: check_font() got an unexpected keyword argument 'progress' 我是这个问题

你这个是字体问题，引掉就行
