### ISSUE TITLE
decouple

### ISSUE THREAD

**Issue by PeterSmith1** [positive666/yolov5_research#22]
## ❔Question

您好，我采用您的swin-head和decouple的yaml，二者结合起来，然后在多个服务器上训练，大概在100epch上出现结果全为0的状态
## Additional context
![image](https://user-images.githubusercontent.com/54202525/163946689-2f5b3ec7-38a9-4416-9bbd-f35159904f15.png)

**Comment by positive666** [comment]
> ## ❔Question
> 您好，我采用您的swin-head和decouple的yaml，二者结合起来，然后在多个服务器上训练，大概在100epch上出现结果全为0的状态
> 
> ## Additional context
> ![image](https://user-images.githubusercontent.com/54202525/163946689-2f5b3ec7-38a9-4416-9bbd-f35159904f15.png)

你好 我建议你先尝试分别各自训练  或者是从新把接偶头训出来 作为pretrain weights，因为接偶头需要从新完整的训练一边，swinV2的搭建有些参数我觉得不合理 等我手头项目验收后我会花时间研究下 会CSDN回复你

**Comment by PeterSmith1** [comment]
> 

谢谢您，对了我还发现，您的代码不只是C3TR报错，C3SPP模块也会报错，好像除了C3块正常使用外，作者其它的C3替换块均出现了这个问题。
![image](https://user-images.githubusercontent.com/54202525/164364185-764d4e9c-db44-4a0d-848a-ae75860a0230.png)

**Comment by positive666** [comment]
> > 
> 
> 谢谢您，对了我还发现，您的代码不只是C3TR报错，C3SPP模块也会报错，好像除了C3块正常使用外，作者其它的C3替换块均出现了这个问题。 ![image](https://user-images.githubusercontent.com/54202525/164364185-764d4e9c-db44-4a0d-848a-ae75860a0230.png)

收到 因为我本地的版本比较多 我晚上拉下来测一下看看

**Comment by positive666** [comment]
> > 
> 
> 谢谢您，对了我还发现，您的代码不只是C3TR报错，C3SPP模块也会报错，好像除了C3块正常使用外，作者其它的C3替换块均出现了这个问题。 ![image](https://user-images.githubusercontent.com/54202525/164364185-764d4e9c-db44-4a0d-848a-ae75860a0230.png)

你是用了V5的算子模块自己搭建出现的错误吗  你说的这两个我没有使用过 这个是调试问题 不知道我理解的情况对吗

**Comment by PeterSmith1** [comment]
> > > 
> > 
> > 
> > 谢谢您，对了我还发现，您的代码不只是C3TR报错，C3SPP模块也会报错，好像除了C3块正常使用外，作者其它的C3替换块均出现了这个问题。 ![image](https://user-images.githubusercontent.com/54202525/164364185-764d4e9c-db44-4a0d-848a-ae75860a0230.png)
> 
> 你是用了V5的算子模块自己搭建出现的错误吗 你说的这两个我没有使用过 这个是调试问题 不知道我理解的情况对吗

对，我用作者的算子去搭建出现的问题，但我直接用的作者代码没有出现这个问题

**Comment by PeterSmith1** [comment]
我当时还以为是swin和作者的ViT有冲突，然后直接在5s上替换一个C3块，依然还是报上面那个错误

**Comment by positive666** [comment]
> 我当时还以为是swin和作者的ViT有冲突，然后直接在5s上替换一个C3块，依然还是报上面那个错误

我还以为我这里有BUG了   你说的这几个我最近有空调一下 我现在在验收项目中 比较忙
