### ISSUE TITLE
添加SE注意力机制

### ISSUE THREAD

**Issue by Xiao-Qi-Guai** [positive666/yolov5_research#23]
## Additional context
我在主干网络的C3模块后面添加SE-Net注意力机制，但是运行detect.py时报如下错误：RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 28 but got size 27 for tensor number 1 in the list.

**Comment by PeterSmith1** [comment]
> ## ❔Question
> ## Additional context
> 我在主干网络的C3模块后面添加SE-Net注意力机制，但是运行detect.py时报如下错误：RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 28 but got size 27 for tensor number 1 in the list.

你可以看一下输出张量，你算一下，博主当时添加过CBAM，我使用是没有这个问题
