### ISSUE TITLE
训练时出现keyError

### ISSUE THREAD

**Issue by wch243294382** [positive666/yolov5_research#24]
AutoAnchor: 5.36 anchors/target, 1.000 Best Possible Recall (BPR). Current anchors are a good fit to dataset ✅
Traceback (most recent call last):
File "train.py", line 678, in
main(opt)
File "train.py", line 575, in main
train(opt.hyp, opt, device, callbacks)
File "train.py", line 305, in train
compute_loss = ComputeLoss(model) # init loss class
File "/home/wch/yolov5_research/utils/loss.py", line 107, in init
self.g2=h['fl_eiou_gamma'] # focal eiou loss gamma
KeyError: 'fl_eiou_gamma'
请问是啥情况

**Comment by positive666** [comment]
> AutoAnchor: 5.36 anchors/target, 1.000 Best Possible Recall (BPR). Current anchors are a good fit to dataset ✅ Traceback (most recent call last): File "train.py", line 678, in main(opt) File "train.py", line 575, in main train(opt.hyp, opt, device, callbacks) File "train.py", line 305, in train compute_loss = ComputeLoss(model) # init loss class File "/home/wch/yolov5_research/utils/loss.py", line 107, in init self.g2=h['fl_eiou_gamma'] # focal eiou loss gamma KeyError: 'fl_eiou_gamma' 请问是啥情况

这不算是BUG ，是我在 超参里额外添加的参数  你命令读取的超参里加入这个值为0.0 就好了
