### ISSUE TITLE
Decoupled Head

### ISSUE THREAD

**Issue by gdxu426** [positive666/yolov5_research#25]
## ❔Question
  博主大大您好，我在使用您的decoupled head 进行实验，采用yolov5s_decoupled.yamy，训练了65个epoch（batch size = 4，其余参数未修改），在visdrone数据集上验证集的map0.5只有0.143，是我什么地方有缺漏忘记调整了吗？

## Additional context
附上我的实验结果如下
   Epoch   gpu_mem       box       obj       cls    labels  img_size
     64/64     1.19G   0.09373    0.1588   0.02641       388       640: 100%|██████████| 1618/1618 [02:45<00:00,  9.75it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 69/69 [00:08<00:00,  7.75it/s]
                 all        548      38759      0.282      0.215      0.143     0.0459

**Comment by PeterSmith1** [comment]
我使用这个结合swin-head直接nan,最近博主有点忙，等他过几天更新下吧

**Comment by PeterSmith1** [comment]
> ## ❔Question
> 博主大大您好，我在使用您的decoupled head 进行实验，采用yolov5s_decoupled.yamy，训练了65个epoch（batch size = 4，其余参数未修改），在visdrone数据集上验证集的map0.5只有0.143，是我什么地方有缺漏忘记调整了吗？
> 
> ## Additional context
> 附上我的实验结果如下 Epoch gpu_mem box obj cls labels img_size 64/64 1.19G 0.09373 0.1588 0.02641 388 640: 100%|██████████| 1618/1618 [02:45<00:00, 9.75it/s] Class Images Labels P R mAP@.5 mAP@.5:.95: 100%|██████████| 69/69 [00:08<00:00, 7.75it/s] all 548 38759 0.282 0.215 0.143 0.0459

你是不是用的权重文件不是6.0版本的，我使用的时候精度没那么低哇

**Comment by gdxu426** [comment]
> > ## ❔Question
> > 博主大大您好，我在使用您的decoupled head 进行实验，采用yolov5s_decoupled.yamy，训练了65个epoch（batch size = 4，其余参数未修改），在visdrone数据集上验证集的map0.5只有0.143，是我什么地方有缺漏忘记调整了吗？
> > ## Additional context
> > 附上我的实验结果如下 Epoch gpu_mem box obj cls labels img_size 64/64 1.19G 0.09373 0.1588 0.02641 388 640: 100%|██████████| 1618/1618 [02:45<00:00, 9.75it/s] Class Images Labels P R mAP@.5 mAP@.5:.95: 100%|██████████| 69/69 [00:08<00:00, 7.75it/s] all 548 38759 0.282 0.215 0.143 0.0459
> 
> 你是不是用的权重文件不是6.0版本的，我使用的时候精度没那么低哇
   我是6.0的权重呀，从默认的下载路径直接下载的，我跑v5s原版也有0.3多

**Comment by positive666** [comment]
> ## ❔Question
> 博主大大您好，我在使用您的decoupled head 进行实验，采用yolov5s_decoupled.yamy，训练了65个epoch（batch size = 4，其余参数未修改），在visdrone数据集上验证集的map0.5只有0.143，是我什么地方有缺漏忘记调整了吗？
> 
> ## Additional context
> 附上我的实验结果如下 Epoch gpu_mem box obj cls labels img_size 64/64 1.19G 0.09373 0.1588 0.02641 388 640: 100%|██████████| 1618/1618 [02:45<00:00, 9.75it/s] Class Images Labels P R mAP@.5 mAP@.5:.95: 100%|██████████| 69/69 [00:08<00:00, 7.75it/s] all 548 38759 0.282 0.215 0.143 0.0459

你epoch太少了 是这样的 你试试300先 因为HEAD结构变了要从新训练

**Comment by positive666** [comment]
> 我使用这个结合swin-head直接nan,最近博主有点忙，等他过几天更新下吧

你可以先把接偶头训出来 加大epoch 然后再改SWINv2

**Comment by Sa-UpWorld** [comment]
> > 我使用这个结合swin-head直接nan,最近博主有点忙，等他过几天更新下吧
> 
> 你可以先把接偶头训出来 加大epoch 然后再改SWINv2

您好，请问您的意思是，先训练好解耦头,然后用解耦头的best模型去跑符合模型吗

**Comment by positive666** [comment]
> > > 我使用这个结合swin-head直接nan,最近博主有点忙，等他过几天更新下吧
> > 
> > 
> > 你可以先把接偶头训出来 加大epoch 然后再改SWINv2
> 
> 您好，请问您的意思是，先训练好解耦头,然后用解耦头的best模型去跑符合模型吗
其实都可以的 比如你改BACKBONE+HEAD，我建议你把HEAD改的先训出来作为初始权重，然后再修改BACKBONE 的方式

**Comment by vzy2d** [comment]
我这边训练这个模型也没法达到README中写的指标，mAP到0.165就基本停住了，看TensorBoard的图表，cls_loss和obj_loss都是上升状态，不知是哪部分有问题，求解答。（我的batchsize是32）
`     Epoch   gpu_mem       box       obj       cls    labels  img_size
   242/299     7.26G   0.09348    0.1531   0.02276       779       640: 100%|██████████| 203/203 [01:16<00:00,  2.66it/s]                                  
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 9/9 [00:04<00:00,  1.83it/s]                      
                 all        548      38759      0.223      0.269      0.165      0.06`
![image](https://user-images.githubusercontent.com/25742504/169286206-5a72257f-3581-4297-a26a-72a7efacf794.png)
![image](https://user-images.githubusercontent.com/25742504/169286124-84f8bb5b-9b4a-4910-8463-fff899c0a460.png)

**Comment by positive666** [comment]
> 我这边训练这个模型也没法达到README中写的指标，mAP到0.165就基本停住了，看TensorBoard的图表，cls_loss和obj_loss都是上升状态，不知是哪部分有问题，求解答。（我的batchsize是32） ` Epoch gpu_mem box obj cls labels img_size 242/299 7.26G 0.09348 0.1531 0.02276 779 640: 100%|██████████| 203/203 [01:16<00:00, 2.66it/s] Class Images Labels P R mAP@.5 mAP@.5:.95: 100%|██████████| 9/9 [00:04<00:00, 1.83it/s] all 548 38759 0.223 0.269 0.165 0.06` ![image](https://user-images.githubusercontent.com/25742504/169286206-5a72257f-3581-4297-a26a-72a7efacf794.png) ![image](https://user-images.githubusercontent.com/25742504/169286124-84f8bb5b-9b4a-4910-8463-fff899c0a460.png)

我在VIRDONE上跑了几百个EPOCH的结果是收敛的，这里不排除代码版本的问题，你可以给一下你的具体参数命令和配置 我在本地复现一下看看，因为本地的代码和上传的区别较大

**Comment by vzy2d** [comment]
> 
我这边的训练命令是`python train.py --data VisDrone.yaml --cfg yolov5s_decoupled.yaml --weights \'\' --batch-size 32`
没有对代码和配置文件做过改动，全默认，麻烦您验证了

**Comment by positive666** [comment]
> > 
> 
> 我这边的训练命令是`python train.py --data VisDrone.yaml --cfg yolov5s_decoupled.yaml --weights \'\' --batch-size 32` 没有对代码和配置文件做过改动，全默认，麻烦您验证了

好的 我看下吧 不过我得先工作~ 你最好有个初始权重 去训练 还有加大下EPOCH再看看

**Comment by JayLuoShui** [comment]
我这边 decoupled 也是效果不好

**Comment by positive666** [comment]
![image](https://user-images.githubusercontent.com/28972473/169729089-7d41f820-030f-4c18-91a6-5dbe3ecf4250.png)
这是我本地的结果，能不能加大EPOCH再看看，如果还有问题 我可以把这部分代码更新下 也有可能是代码问题

**Comment by vzy2d** [comment]
> ![image](https://user-images.githubusercontent.com/28972473/169729089-7d41f820-030f-4c18-91a6-5dbe3ecf4250.png) ![image](https://user-images.githubusercontent.com/28972473/169729439-13dd52f8-dab0-4dfa-a7c0-79c82aad7a49.png)
> 
> 这是我本地的结果，能不能加大EPOCH再看看，如果还有问题 我可以把这部分代码更新下 也有可能是代码问题

我这边后续有继续再训了300个epoch，也就是总共训了600.   有提升一些到了0.18，但是和您的结果还是有差距，可能需要更新一下最新的代码了

**Comment by positive666** [comment]
> > ![image](https://user-images.githubusercontent.com/28972473/169729089-7d41f820-030f-4c18-91a6-5dbe3ecf4250.png) ![image](https://user-images.githubusercontent.com/28972473/169729439-13dd52f8-dab0-4dfa-a7c0-79c82aad7a49.png)
> > 这是我本地的结果，能不能加大EPOCH再看看，如果还有问题 我可以把这部分代码更新下 也有可能是代码问题
> 
> 我这边后续有继续再训了300个epoch，也就是总共训了600. 有提升一些到了0.18，但是和您的结果还是有差距，可能需要更新一下最新的代码了

em..可以 但是我需要自己再验证下线上这个版本的代码 如果有问题我就更新
