### ISSUE TITLE
botnet的添加问题

### ISSUE THREAD

**Issue by songjiahao-wq** [positive666/yolov5_research#26]
## ❔Question
我发现博主大大再添加mhsa时后面并未加BN和silu层，这是有什么深意吗？

**Comment by positive666** [comment]
> ## ❔Question
> 我发现博主大大再添加mhsa时后面并未加BN和silu层，这是有什么深意吗？
> 
> ## Additional context

这..其实.并没有什么深意 哈 是去年那时候我刚做transformer迁移的第一个尝试，那时候的意图是混合token,现在做骨干探究的话，就是三个路线两大思想，你可以试试SWIN2 先组建几层不过可能还有些问题 没彻底改善，比如全SWIN2的训练问题 等我忙完手头工作研究研究
