### ISSUE TITLE
请问swinV2训练评估一直为零正常吗？

### ISSUE THREAD

**Issue by xiaoxiaolu1111** [positive666/yolov5_research#28]
[image](![2022-05-09 18-02-56 的屏幕截图](https://user-images.githubusercontent.com/88141595/167388780-9cea6cc9-5804-4d56-aad4-e3a8bcc89429.png))

**Comment by positive666** [comment]
> [image](![2022-05-09 18-02-56 的屏幕截图](https://user-images.githubusercontent.com/88141595/167388780-9cea6cc9-5804-4d56-aad4-e3a8bcc89429.png))

收到 等我有空看一下 你试试作为某几层可以训练吗，预训练权重是什么？

**Comment by JayLuoShui** [comment]
这个难道很难训练吗 这需要加入预训练权重吗

**Comment by positive666** [comment]
> 这个难道很难训练吗 这需要加入预训练权重吗

你可以先自己训练一个预权重 （排除梯度消失的问题）

**Comment by JayLuoShui** [comment]
> > 这个难道很难训练吗 这需要加入预训练权重吗
> 
> 你可以先自己训练一个预权重 （排除梯度消失的问题）

雀食可先用yolo的权重训练，但是很快loss就nan，然后再用已经训练保持的best.pt 就可以继续训练了

**Comment by positive666** [comment]
> > > 这个难道很难训练吗 这需要加入预训练权重吗
> > 
> > 
> > 你可以先自己训练一个预权重 （排除梯度消失的问题）
> 
> 雀食可先用yolo的权重训练，但是很快loss就nan，然后再用已经训练保持的best.pt 就可以继续训练了

OK 你训练的是哪个结构

**Comment by JayLuoShui** [comment]
> 

用的自己数据集训练的swinv2-head

**Comment by zhaoziyu513** [comment]
我现在也是这个情况，一直是prmap是0，或者0.0005左右，而且loss也一直是nan，用的swinv2_head。请问大佬这个应该怎么解决，非常感谢。
