### ISSUE TITLE
运行ASFF_Detect出错

### ISSUE THREAD

**Issue by wenjunx** [positive666/yolov5_research#29]
## Additional context
大佬，我加了ASFF_Detect,出现报错，ASFF AttributeError: 'Model' object has no attribute 'stride',请问怎么解决，用的是github上的代码

**Comment by positive666** [comment]
> ## ❔Question
> ## Additional context
> 大佬，我加了ASFF_Detect,出现报错，ASFF AttributeError: 'Model' object has no attribute 'stride',请问怎么解决，用的是github上的代码

你是博客的吗  解决了吧应该？
