### ISSUE TITLE
SwinV2.yaml运行报错

### ISSUE THREAD

**Issue by Sa-UpWorld** [positive666/yolov5_research#3]
## ❔Question
 File "D:\Python\yolov5\utils\datasets.py", line 420, in __init__
 cache, exists = np.load(cache_path, allow_pickle=True).item(), True  # load dict
## Additional context
作者您好，请问仓库拉取后跑SwinV2.yaml为什么报错啊,是目前没有上传完整吗？而且我看到计算量很大，请问作者您试过将SwinTransformer作为类似C3卷积块的算子替换C3吗

**Comment by positive666** [comment]
> ## ❔Question
> File "D:\Python\yolov5\utils\datasets.py", line 420, in **init** cache, exists = np.load(cache_path, allow_pickle=True).item(), True # load dict
> 
> ## Additional context
> 作者您好，请问仓库拉取后跑SwinV2.yaml为什么报错啊,是目前没有上传完整吗？而且我看到计算量很大，请问作者您试过将SwinTransformer作为类似C3卷积块的算子替换C3吗

你好现在还有这个问题嘛？ 我去年用的BOTNET那个做的类似的思路  是transformer替换了3X3卷积 并不是swin，整个backbone肯定比较大，我的意思是放出的YAML是个参考，两种探索：1.你可以把NECK换成CONV的，使用swinv2的backbone，但是你的学习率和优化器都要从新设置，因为你骨干重置了 2：老套路:可以把SWINV2作为一个注意力层，这种形式比较好操作 也比较好训练；

**Comment by Sa-UpWorld** [comment]
> > ## ❔Question
> > File "D:\Python\yolov5\utils\datasets.py", line 420, in **init** cache, exists = np.load(cache_path, allow_pickle=True).item(), True # load dict
> > ## Additional context
> > 作者您好，请问仓库拉取后跑SwinV2.yaml为什么报错啊,是目前没有上传完整吗？而且我看到计算量很大，请问作者您试过将SwinTransformer作为类似C3卷积块的算子替换C3吗
> 
> 你好现在还有这个问题嘛？ 我去年用的BOTNET那个做的类似的思路 是transformer替换了3X3卷积 并不是swin，整个backbone肯定比较大，我的意思是放出的YAML是个参考，两种探索：1.你可以把NECK换成CONV的，使用swinv2的backbone，但是你的学习率和优化器都要从新设置，因为你骨干重置了 2：老套路:可以把SWINV2作为一个注意力层，这种形式比较好操作 也比较好训练；

我尝试将Swin作为算子替换C3卷积块，但目前遇到张量维度错误一直没有解决，请问您之后还会更Swin作为算子的替换吗

**Comment by positive666** [comment]
> > > ## ❔Question
> > > File "D:\Python\yolov5\utils\datasets.py", line 420, in **init** cache, exists = np.load(cache_path, allow_pickle=True).item(), True # load dict
> > > ## Additional context
> > > 作者您好，请问仓库拉取后跑SwinV2.yaml为什么报错啊,是目前没有上传完整吗？而且我看到计算量很大，请问作者您试过将SwinTransformer作为类似C3卷积块的算子替换C3吗
> > 
> > 
> > 你好现在还有这个问题嘛？ 我去年用的BOTNET那个做的类似的思路 是transformer替换了3X3卷积 并不是swin，整个backbone肯定比较大，我的意思是放出的YAML是个参考，两种探索：1.你可以把NECK换成CONV的，使用swinv2的backbone，但是你的学习率和优化器都要从新设置，因为你骨干重置了 2：老套路:可以把SWINV2作为一个注意力层，这种形式比较好操作 也比较好训练；
> 
> 我尝试将Swin作为算子替换C3卷积块，但目前遇到张量维度错误一直没有解决，请问您之后还会更Swin作为算子的替换吗

现在就有了啊 你可以自己构建YAML

**Comment by Sa-UpWorld** [comment]
> > > > ## ❔Question
> > > > File "D:\Python\yolov5\utils\datasets.py", line 420, in **init** cache, exists = np.load(cache_path, allow_pickle=True).item(), True # load dict
> > > > ## Additional context
> > > > 作者您好，请问仓库拉取后跑SwinV2.yaml为什么报错啊,是目前没有上传完整吗？而且我看到计算量很大，请问作者您试过将SwinTransformer作为类似C3卷积块的算子替换C3吗
> > > 
> > > 
> > > 你好现在还有这个问题嘛？ 我去年用的BOTNET那个做的类似的思路 是transformer替换了3X3卷积 并不是swin，整个backbone肯定比较大，我的意思是放出的YAML是个参考，两种探索：1.你可以把NECK换成CONV的，使用swinv2的backbone，但是你的学习率和优化器都要从新设置，因为你骨干重置了 2：老套路:可以把SWINV2作为一个注意力层，这种形式比较好操作 也比较好训练；
> > 
> > 
> > 我尝试将Swin作为算子替换C3卷积块，但目前遇到张量维度错误一直没有解决，请问您之后还会更Swin作为算子的替换吗
> 
> 现在就有了啊 你可以自己构建YAML

您可以分享一个Swin作为C3算子的yaml吗，看了您common内的Swin程序，和我找到的其他方法不太一样，我找到的另一个方法是将Swin直接封装为C3TR那样的块用于替换，我的邮箱是1440797327@qq.com，感谢作者

**Comment by positive666** [comment]
> > > > > ## ❔Question
> > > > > File "D:\Python\yolov5\utils\datasets.py", line 420, in **init** cache, exists = np.load(cache_path, allow_pickle=True).item(), True # load dict
> > > > > ## Additional context
> > > > > 作者您好，请问仓库拉取后跑SwinV2.yaml为什么报错啊,是目前没有上传完整吗？而且我看到计算量很大，请问作者您试过将SwinTransformer作为类似C3卷积块的算子替换C3吗
> > > > 
> > > > 
> > > > 你好现在还有这个问题嘛？ 我去年用的BOTNET那个做的类似的思路 是transformer替换了3X3卷积 并不是swin，整个backbone肯定比较大，我的意思是放出的YAML是个参考，两种探索：1.你可以把NECK换成CONV的，使用swinv2的backbone，但是你的学习率和优化器都要从新设置，因为你骨干重置了 2：老套路:可以把SWINV2作为一个注意力层，这种形式比较好操作 也比较好训练；
> > > 
> > > 
> > > 我尝试将Swin作为算子替换C3卷积块，但目前遇到张量维度错误一直没有解决，请问您之后还会更Swin作为算子的替换吗
> > 
> > 
> > 现在就有了啊 你可以自己构建YAML
> 
> 您可以分享一个Swin作为C3算子的yaml吗，看了您common内的Swin程序，和我找到的其他方法不太一样，我找到的另一个方法是将Swin直接封装为C3TR那样的块用于替换，我的邮箱是[1440797327@qq.com](mailto:1440797327@qq.com)，感谢作者

好的 没问题 看时间 我参考了SWINV2的设计点，并不是原版的SWIN1.0

**Comment by Sa-UpWorld** [comment]
> > > > > > ## ❔Question
> > > > > > File "D:\Python\yolov5\utils\datasets.py", line 420, in **init** cache, exists = np.load(cache_path, allow_pickle=True).item(), True # load dict
> > > > > > ## Additional context
> > > > > > 作者您好，请问仓库拉取后跑SwinV2.yaml为什么报错啊,是目前没有上传完整吗？而且我看到计算量很大，请问作者您试过将SwinTransformer作为类似C3卷积块的算子替换C3吗
> > > > > 
> > > > > 
> > > > > 你好现在还有这个问题嘛？ 我去年用的BOTNET那个做的类似的思路 是transformer替换了3X3卷积 并不是swin，整个backbone肯定比较大，我的意思是放出的YAML是个参考，两种探索：1.你可以把NECK换成CONV的，使用swinv2的backbone，但是你的学习率和优化器都要从新设置，因为你骨干重置了 2：老套路:可以把SWINV2作为一个注意力层，这种形式比较好操作 也比较好训练；
> > > > 
> > > > 
> > > > 我尝试将Swin作为算子替换C3卷积块，但目前遇到张量维度错误一直没有解决，请问您之后还会更Swin作为算子的替换吗
> > > 
> > > 
> > > 现在就有了啊 你可以自己构建YAML
> > 
> > 
> > 您可以分享一个Swin作为C3算子的yaml吗，看了您common内的Swin程序，和我找到的其他方法不太一样，我找到的另一个方法是将Swin直接封装为C3TR那样的块用于替换，我的邮箱是[1440797327@qq.com](mailto:1440797327@qq.com)，感谢作者
> 
> 好的 没问题 看时间 我参考了SWINV2的设计点，并不是原版的SWIN1.0
期待您的更新
