### ISSUE TITLE
About DCN+yolov5

### ISSUE THREAD

**Issue by supperbadguy** [positive666/yolov5_research#31]
## ❔Question

Dear Writer, would you like to add DCN moudel into this YOLOv5 project? If you have created it, where can I find it?

**Comment by positive666** [comment]
> ## ❔Question
> Dear Writer, would you like to add DCN moudel into this YOLOv5 project? If you have created it, where can I find it?
> 
> ## Additional context

dcn  not introduce, but later can consider

**Comment by Sa-UpWorld** [comment]
> > ## ❔问题
> > 亲爱的作者，您想将 DCN moudel 添加到这个 YOLOv5 项目中吗？如果您创建了它，我在哪里可以找到它？
> > ## 附加上下文
> 
> dcn不介绍，但以后可以考虑

您好，请问后续会介绍京东开源的CoT吗
