### ISSUE TITLE
导入其他的C3模块报错

### ISSUE THREAD

**Issue by zms1304210716** [positive666/yolov5_research#32]
你好，在实验中使用C3模块是可以的，使用其他的融合的C3模块就报这样的错误：TypeError: empty(): argument 'size' must be tuple of ints, but found element of type float at pos 2      这是什么原因呢

**Comment by positive666** [comment]
> 你好，在实验中使用C3模块是可以的，使用其他的融合的C3模块就报这样的错误：TypeError: empty(): argument 'size' must be tuple of ints, but found element of type float at pos 2 这是什么原因呢

传参错了应该是 你可以拉我新更的代码
