### ISSUE TITLE
x6+ASFF报错

### ISSUE THREAD

**Issue by infrontofme** [positive666/yolov5_research#33]
## ❔Question
将x6模型文件的检测层，替换成ASFF_Detect报错，请问现在ASFF还不支持P6系列的模型吗？

**Comment by positive666** [comment]
> ## ❔Question
> 将x6模型文件的检测层，替换成ASFF_Detect报错，请问现在ASFF还不支持P6系列的模型吗？
> 
> ## Additional context

那个是三层的不支持呢 你可以自己搭配一个
