### ISSUE TITLE
SWINV2

### ISSUE THREAD

**Issue by PeterSmith1** [positive666/yolov5_research#34]
## Additional context
博主您好，现在swinV2已经开源了，您的SWINV2的backbone如何去使用官方的V2的预训练权重呢

**Comment by positive666** [comment]
> ## ❔Question
> ## Additional context
> 博主您好，现在swinV2已经开源了，您的SWINV2的backbone如何去使用官方的V2的预训练权重呢

开源的我还没看 scrath一个 就行，我的估计和swin不是完全一样的结构 ，使用自己搭建的最好还是自己训练一个
