### ISSUE TITLE
解耦头

### ISSUE THREAD

**Issue by PeterSmith1** [positive666/yolov5_research#35]
## Additional context
按您修改的解耦头改到自己代码还是报错，显示  self.m = nn.ModuleList(DecoupledHead(x,nc,anchors) for x in ch) if self.decoupled else nn.ModuleList(nn.Conv2d(x, self.no * self.na, 1) for x in ch)  # output conv
TypeError: 'bool' object is not iterable

**Comment by positive666** [comment]
> ## ❔Question
> ## Additional context
> 按您修改的解耦头改到自己代码还是报错，显示 self.m = nn.ModuleList(DecoupledHead(x,nc,anchors) for x in ch) if self.decoupled else nn.ModuleList(nn.Conv2d(x, self.no * self.na, 1) for x in ch) # output conv TypeError: 'bool' object is not iterable

今晚9点前修复

**Comment by positive666** [comment]
已经修复了 是我的问题
