### ISSUE TITLE
请教object has no attribute 'stride'您是如何解决的？？

### ISSUE THREAD

**Issue by ericzhang1994** [positive666/yolov5_research#39]
## ❔Question
: 'Model' object has no attribute 'stride'这个问题您已经解决了，但是非常好奇，想请教您是如何解决这个问题的呢？这个问题的原因是什么？可以解答下嘛？谢谢您

**Comment by positive666** [comment]
最近事情比较杂，这个错误  可能是你的yaml定义结构导致的问题，具体不知道你是哪个机构引起来的 有几种情况需要反复debug, 一般就是修改yolo.py里的模型初始化的几处  你运行结构时候 他会先进行一次推理这时候有一些参数会初始化 具体你可以看下我的yolo.py和官方有什么不同 ,举个例子比如这段
![image](https://user-images.githubusercontent.com/28972473/172983667-f128456f-dee7-4ced-9b93-c3c589ccd1f5.png)
