### ISSUE TITLE
您好，请问下mhsa使用位置编码，调试显示content和position维度相同，但运行会报维度不匹配的问题是什么原因呢

### ISSUE THREAD

**Issue by Seperendity** [positive666/yolov5_research#4]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## To Reproduce (REQUIRED)

Input:
```
import torch

a = torch.tensor([5])
c = a / 0
```

Output:
```
Traceback (most recent call last):
  File "/Users/glennjocher/opt/anaconda3/envs/env1/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-be04c762b799>", line 5, in <module>
    c = a / 0
RuntimeError: ZeroDivisionError
```

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

**Comment by positive666** [comment]
em..整个是根据你的通道数设定的，因为在您的实验里开启了MHSA后，可学习的位置编码是相对固定的维度，导致了tensor维度会错，两种解决方式：一种参考我添加的swin,自己手动调整；其次是在函数里写成动态更新分辨率，因为出了swin和我手头项目太多就搁置了优化  看时间我后会更新这个问题；目前的代码里是默认取消了，因为多头注意力机制在深层的使用是为了降低计算量，且那个位置的编码信息可能对模型的影响不大了

**Comment by Seperendity** [comment]
非常感谢您的解答，我尝试一下您说的方案。关于位置编码我看很多论文加上位置编码检测效果往往会更好，所以想看看跑跑看看。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "positive666/yolov5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 下午3:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [positive666/yolov5] 您好，请问下mhsa使用位置编码，调试显示content和position维度相同，但运行会报维度不匹配的问题是什么原因呢 (Issue #4)





 
em..整个是根据你的通道数设定的，因为在您的实验里开启了MHSA后，可学习的位置编码是相对固定的维度，导致了tensor维度会错，两种解决方式：一种参考我添加的swin,自己手动调整；其次是在函数里写成动态更新分辨率，因为出了swin和我手头项目太多就搁置了优化  看时间我后会更新这个问题；目前的代码里是默认取消了，因为多头注意力机制在深层的使用是为了降低计算量，且那个位置的编码信息可能对模型的影响不大了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by positive666** [comment]
> 非常感谢您的解答，我尝试一下您说的方案。关于位置编码我看很多论文加上位置编码检测效果往往会更好，所以想看看跑跑看看。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "positive666/yolov5" ***@***.***&gt;; 发送时间:&nbsp;2022年3月10日(星期四) 下午3:52 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [positive666/yolov5] 您好，请问下mhsa使用位置编码，调试显示content和position维度相同，但运行会报维度不匹配的问题是什么原因呢 (Issue #4) em..整个是根据你的通道数设定的，因为在您的实验里开启了MHSA后，可学习的位置编码是相对固定的维度，导致了tensor维度会错，两种解决方式：一种参考我添加的swin,自己手动调整；其次是在函数里写成动态更新分辨率，因为出了swin和我手头项目太多就搁置了优化 看时间我后会更新这个问题；目前的代码里是默认取消了，因为多头注意力机制在深层的使用是为了降低计算量，且那个位置的编码信息可能对模型的影响不大了 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这个不好说，因为你提的这个思路 我去年就是这么想的 但是后来我想了下，在模型深层的Positon embeds 也许没有那么重要  我认为混合的形式其实本质上意义不大， 浅层的CNN也许可以做的很好了 如果不用swin的话 那么sA也只能作为深层用了 因为SWIN设计也只是仿照CNN的层次化 对于featuremap核心还是sA的作用和positon emebeds，但是这个是特殊情况，所以深层我认为没有必要，理论上应该推翻，直接一个全transformer的backbone才有挑战 类似和swin一样。   swinv2的位置编码方式也是从新把1.0的推翻了

**Comment by positive666** [comment]
> 嗯您分析的很有道理，不过位置编码这块的解释性还是挺弱的，还是要在一些通用型数据集上验证一下。直觉上我觉得深层学到的这些语义之间的相对关系对网络还是很有帮助的，比如BOTNet和CotNet这两篇论文在检测任务上的实验
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "positive666/yolov5" ***@***.***&gt;; 发送时间:&nbsp;2022年3月10日(星期四) 下午5:47 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [positive666/yolov5] 您好，请问下mhsa使用位置编码，调试显示content和position维度相同，但运行会报维度不匹配的问题是什么原因呢 (Issue #4) 非常感谢您的解答，我尝试一下您说的方案。关于位置编码我看很多论文加上位置编码检测效果往往会更好，所以想看看跑跑看看。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "positive666/yolov5" @.&gt;; 发送时间:&nbsp;2022年3月10日(星期四) 下午3:52 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [positive666/yolov5] 您好，请问下mhsa使用位置编码，调试显示content和position维度相同，但运行会报维度不匹配的问题是什么原因呢 (Issue #4) em..整个是根据你的通道数设定的，因为在您的实验里开启了MHSA后，可学习的位置编码是相对固定的维度，导致了tensor维度会错，两种解决方式：一种参考我添加的swin,自己手动调整；其次是在函数里写成动态更新分辨率，因为出了swin和我手头项目太多就搁置了优化 看时间我后会更新这个问题；目前的代码里是默认取消了，因为多头注意力机制在深层的使用是为了降低计算量，且那个位置的编码信息可能对模型的影响不大了 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt; 这个不好说，因为你提的这个思路 我去年就是这么想的 但是后来我想了下，在模型深层的Positon embeds 也许没有那么重要 我认为混合的形式其实本质上意义不大， 浅层的CNN也许可以做的很好了 如果不用swin的话 那么sA也只能作为深层用了 因为SWIN设计也只是仿照CNN的层次化 对于featuremap核心还是sA的作用和positon emebeds，但是这个是特殊情况，所以深层我认为没有必要，理论上应该推翻，直接一个全transformer的backbone才有挑战 类似和swin一样。 swinv2的位置编码方式也是从新把1.0的推翻了 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

em.这个结论我也是参考别人的，忘记了是参考哪个文章的实验了，不过现在还是CNN主流 swin也好 GFLOPs还是大了点（ 目前使用角度的话 就是作为插件层自己设计使用的话是最好训练最容易出成果的 ） 理论上都强调自注意力层的长距离依赖  还有就是其实你想提高模型特征提取的性能 可以多做shortcut和残差的设计 就现在设计要考虑实用性角度：有效且同时减小Gflops
