### ISSUE TITLE
将yolos-asff改成yolom-asff或yolol-asff问题

### ISSUE THREAD

**Issue by ericzhang1994** [positive666/yolov5_research#40]
## ❔Question
我将yolos-asff改成yolom-asff报错这个问题，请教一下修改思路，是不是要在yolo.py和common里对asff进行特定的修改呢？
Given groups=1, weight of size [128, 512, 1, 1], expected input[1, 768, 8, 8] to have 512 channels, but got 768 channels instead
万分感谢您！！我的邮箱是918255802@qq.com 如果方便可以邮箱交流下！谢谢！！

**Comment by ericzhang1994** [comment]
抱歉抱歉！邮箱留错了，是918255802@qq.com，给一点思路就可以，因为我目前找不到到底是哪一层的通道没有匹配上

**Comment by positive666** [comment]
> 抱歉抱歉！邮箱留错了，是[918255802@qq.com](mailto:918255802@qq.com)，给一点思路就可以，因为我目前找不到到底是哪一层的通道没有匹配上

你直接换成ASFF_Detect 不可以嘛在YAML里?

**Comment by ericzhang1994** [comment]
> > 抱歉抱歉！邮箱留错了，是[918255802@qq.com](mailto:918255802@qq.com)，给一点思路就可以，因为我目前找不到到底是哪一层的通道没有匹配上
> 
> 你直接换成ASFF_Detect 不可以嘛在YAML里?

我改过了，在yolov5m的YAML里改成ASFF_Detect,但是报错通道维度不匹配，我打印了一下不同层的维度，但是没找到哪里的问题，报错：Given groups=1, weight of size [128, 512, 1, 1], expected input[1, 768, 8, 8] to have 512 channels, but got 768 channels instead，难道这个只能在s中用吗？m和l都用不了啊，还请大神给点思路！！

**Comment by ericzhang1994** [comment]
> > 抱歉抱歉！邮箱留错了，是[918255802@qq.com](mailto:918255802@qq.com)，给一点思路就可以，因为我目前找不到到底是哪一层的通道没有匹配上
> 
> 你直接换成ASFF_Detect 不可以嘛在YAML里?

我换成yolov5l就是这个错误，Given groups=1, weight of size [128, 512, 1, 1], expected input[1, 1024, 8, 8] to have 512 channels, but got 1024 channels instead   从m的768变成了l的1024，大牛我怀疑是不是和最后输出层维度不一致有关系，但是我不确定到底在哪里改

**Comment by ericzhang1994** [comment]
> > 抱歉抱歉！邮箱留错了，是[918255802@qq.com](mailto:918255802@qq.com)，给一点思路就可以，因为我目前找不到到底是哪一层的通道没有匹配上
> 
> 你直接换成ASFF_Detect 不可以嘛在YAML里?

大神！我解决了！是yolo.py里
![image](https://user-images.githubusercontent.com/43285486/173300165-2fbdc552-4ea7-4717-94a3-7305f72442fb.png)
要把multiplier对应修改了，之前太粗心了，没有看到！！

**Comment by bzha5848** [comment]
我按照这里的方法修改了yolom-asff, 但是和现有的yolom相比准确率下降了，是哪里有问题吗？
