### ISSUE TITLE
yolov5可以结合fcanet吗请问

### ISSUE THREAD

**Issue by yehaizi1** [positive666/yolov5_research#41]

**Comment by positive666** [comment]
> ## ❔Question
> ## Additional context

 这也是这个项目分享的初衷，只是在这个代码框架下 模型本身是根据你自己适配设计的可以

**Comment by yehaizi1** [comment]
我在FCA开源代码中找到fcanet.py.将其中的两个fca的class直接提取出来，加入到我yolov5的网络结构中，这样算结合了吗请问。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月15日(星期三) 中午11:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [positive666/yolov5_research] yolov5可以结合fcanet吗请问 (Issue #41)





  
❔Question
 
Additional context
  
这也是这个项目分享的初衷，只是在这个代码框架下 模型本身是根据你自己适配设计的可以

**Comment by positive666** [comment]
> 我在FCA开源代码中找到fcanet.py.将其中的两个fca的class直接提取出来，加入到我yolov5的网络结构中，这样算结合了吗请问。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年6月15日(星期三) 中午11:40 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [positive666/yolov5_research] yolov5可以结合fcanet吗请问 (Issue #41) ❔Question Additional context 这也是这个项目分享的初衷，只是在这个代码框架下 模型本身是根据你自己适配设计的可以 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我不了解你说的机构 如果只是一个算子层是没问题的

**Comment by yao-zheng-yi** [comment]
> 我在FCA开源代码中找到fcanet.py.将其中的两个fca的class直接提取出来，加入到我yolov5的网络结构中，这样算结合了吗请问。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年6月15日(星期三) 中午11:40 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [positive666/yolov5_research] yolov5可以结合fcanet吗请问 (Issue #41) ❔Question Additional context 这也是这个项目分享的初衷，只是在这个代码框架下 模型本身是根据你自己适配设计的可以 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，请问你添加成功了吗，加入fcanet对yolov5的mAP有提升吗
