### ISSUE TITLE
模型搭建，会报错  0                -1  1      3264  models.common.PatchEmbed                [4, 3, 64] D:\conda\envs\py630\lib\site-packages\torch\functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\bu ilder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:2895.)

### ISSUE THREAD

**Issue by xiaoaleiBLUE** [positive666/yolov5_research#48]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## To Reproduce (REQUIRED)

Input:
```
import torch

a = torch.tensor([5])
c = a / 0
```

Output:
```
Traceback (most recent call last):
  File "/Users/glennjocher/opt/anaconda3/envs/env1/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-be04c762b799>", line 5, in <module>
    c = a / 0
RuntimeError: ZeroDivisionError
```

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

**Comment by xiaoaleiBLUE** [comment]
然后训练跑个一次直接报错退出训练，想问一下大家怎么解决

**Comment by positive666** [comment]
> 然后训练跑个一次直接报错退出训练，想问一下大家怎么解决

你的第一个BUG是你自己写的测试脚本吗 ？

**Comment by positive666** [comment]
> 然后训练跑个一次直接报错退出训练，想问一下大家怎么解决

请告诉我你运行的命令

**Comment by positive666** [comment]
我换了CI 等我更新后你再拉新代码
