### ISSUE TITLE
作者您好，您在自己的数据集上测试过biFPN吗？效果怎样

### ISSUE THREAD

**Issue by Wanghe1997** [positive666/yolov5_research#5]
在官方yolov5-v6.0中的models/hub文件夹下，作者提供了一个yolov5-bifpn.yaml模型配置文件。我看了下，官方作者只在head的检测中等目标（medium）的检测头加入了bifpn，请问作者您知道怎么在小目标检测头也添加bifpn吗？如果您有相关的yaml文件，可以提供一下吗？谢谢
我问的配置文件的链接：[https://github.com/ultralytics/yolov5/blob/v6.0/models/hub/yolov5-bifpn.yaml](url)

**Comment by Wanghe1997** [comment]
其实我不知道这个yaml文件只是在P4融合了bifpn，还是P3、P4、P5都融合了呢？作者您能否给我解答下？谢谢您。

**Comment by hukaick** [comment]
我在自己的小数据上用P6的BIFPN S的模型提点了  但是别的数据集反倒低了

**Comment by positive666** [comment]
> 在官方yolov5-v6.0中的models/hub文件夹下，作者提供了一个yolov5-bifpn.yaml模型配置文件。我看了下，官方作者只在head的检测中等目标（medium）的检测头加入了bifpn，请问作者您知道怎么在小目标检测头也添加bifpn吗？如果您有相关的yaml文件，可以提供一下吗？谢谢 我问的配置文件的链接：[https://github.com/ultralytics/yolov5/blob/v6.0/models/hub/yolov5-bifpn.yaml](url)
可以的，等我有空写一个哈，他和我的方式不一样，每层融合代码用的是权重ADD， V5作者只是一个连接方式应该，小目标的话 之前网友反馈用的YOLOV5S P6+ BIFPN+坐标注意力机制  ，其实我有空是在考虑汇总下大家的数据表现，平时业务太多了 都是抽空更一下

**Comment by positive666** [comment]
> 其实我不知道这个yaml文件只是在P4融合了bifpn，还是P3、P4、P5都融合了呢？作者您能否给我解答下？谢谢您。

我个人认为融合方式 没有必要过度考究， 遵循的原则是深浅结合和重复融合，上采样可以换成转置卷积

**Comment by Wanghe1997** [comment]
> > 在官方yolov5-v6.0中的models/hub文件夹下，作者提供了一个yolov5-bifpn.yaml模型配置文件。我看了下，官方作者只在head的检测中等目标（medium）的检测头加入了bifpn，请问作者您知道怎么在小目标检测头也添加bifpn吗？如果您有相关的yaml文件，可以提供一下吗？谢谢 我问的配置文件的链接：[https://github.com/ultralytics/yolov5/blob/v6.0/models/hub/yolov5-bifpn.yaml](url)
> > 可以的，等我有空写一个哈，他和我的方式不一样，每层融合代码用的是权重ADD， V5作者只是一个连接方式应该，小目标的话 之前网友反馈用的YOLOV5S P6+ BIFPN+坐标注意力机制  ，其实我有空是在考虑汇总下大家的数据表现，平时业务太多了 都是抽空更一下

好的，谢谢老哥。您能不能在最基本的yolov5s.yaml的基础上，对P3、P4加入bifpn，重新写个yaml文件呢？就不包括P6了

**Comment by positive666** [comment]
> > > 在官方yolov5-v6.0中的models/hub文件夹下，作者提供了一个yolov5-bifpn.yaml模型配置文件。我看了下，官方作者只在head的检测中等目标（medium）的检测头加入了bifpn，请问作者您知道怎么在小目标检测头也添加bifpn吗？如果您有相关的yaml文件，可以提供一下吗？谢谢 我问的配置文件的链接：[https://github.com/ultralytics/yolov5/blob/v6.0/models/hub/yolov5-bifpn.yaml](url)
> > > 可以的，等我有空写一个哈，他和我的方式不一样，每层融合代码用的是权重ADD， V5作者只是一个连接方式应该，小目标的话 之前网友反馈用的YOLOV5S P6+ BIFPN+坐标注意力机制  ，其实我有空是在考虑汇总下大家的数据表现，平时业务太多了 都是抽空更一下
> 
> 好的，谢谢老哥。您能不能在最基本的yolov5s.yaml的基础上，对P3、P4加入bifpn，重新写个yaml文件呢？就不包括P6了

你可以参考下yolov5 P5的YAML  我有空会更 太忙了。。

**Comment by Wanghe1997** [comment]
> > > > 在官方yolov5-v6.0中的models/hub文件夹下，作者提供了一个yolov5-bifpn.yaml模型配置文件。我看了下，官方作者只在head的检测中等目标（medium）的检测头加入了bifpn，请问作者您知道怎么在小目标检测头也添加bifpn吗？如果您有相关的yaml文件，可以提供一下吗？谢谢 我问的配置文件的链接：[https://github.com/ultralytics/yolov5/blob/v6.0/models/hub/yolov5-bifpn.yaml](url)
> > > > 可以的，等我有空写一个哈，他和我的方式不一样，每层融合代码用的是权重ADD， V5作者只是一个连接方式应该，小目标的话 之前网友反馈用的YOLOV5S P6+ BIFPN+坐标注意力机制  ，其实我有空是在考虑汇总下大家的数据表现，平时业务太多了 都是抽空更一下
> > 
> > 
> > 好的，谢谢老哥。您能不能在最基本的yolov5s.yaml的基础上，对P3、P4加入bifpn，重新写个yaml文件呢？就不包括P6了
> 
> 你可以参考下yolov5 P5的YAML 我有空会更 太忙了。。

谢谢老哥，我实现了

**Comment by positive666** [comment]
> > > > > 在官方yolov5-v6.0中的models/hub文件夹下，作者提供了一个yolov5-bifpn.yaml模型配置文件。我看了下，官方作者只在head的检测中等目标（medium）的检测头加入了bifpn，请问作者您知道怎么在小目标检测头也添加bifpn吗？如果您有相关的yaml文件，可以提供一下吗？谢谢 我问的配置文件的链接：[https://github.com/ultralytics/yolov5/blob/v6.0/models/hub/yolov5-bifpn.yaml](url)
> > > > > 可以的，等我有空写一个哈，他和我的方式不一样，每层融合代码用的是权重ADD， V5作者只是一个连接方式应该，小目标的话 之前网友反馈用的YOLOV5S P6+ BIFPN+坐标注意力机制  ，其实我有空是在考虑汇总下大家的数据表现，平时业务太多了 都是抽空更一下
> > > 
> > > 
> > > 好的，谢谢老哥。您能不能在最基本的yolov5s.yaml的基础上，对P3、P4加入bifpn，重新写个yaml文件呢？就不包括P6了
> > 
> > 
> > 你可以参考下yolov5 P5的YAML 我有空会更 太忙了。。
> 
> 谢谢老哥，我实现了

BIFPN 的权重参数修复了
