### ISSUE TITLE
训练集验证集测试集

### ISSUE THREAD

**Issue by HelloYangwudi** [positive666/yolov5_research#54]
## ❔Question
请问Yolov5 6.1版本的代码中，训练集验证集是分开训练和验证吗   那么测试集怎么用呢？

**Comment by positive666** [comment]
> ## ❔Question
> 请问Yolov5 6.1版本的代码中，训练集验证集是分开训练和验证吗 那么测试集怎么用呢？
> 
> ## Additional context

训练的时候 会每个epoch结束调用val.py里的验证  是这个逻辑  测试用val.py
