### ISSUE TITLE
YOLOm-ASFF问题

### ISSUE THREAD

**Issue by bzha5848** [positive666/yolov5_research#56]
你好！

我在修改的时候遇到如下问题，请问有什么办法可以解决吗？
![image](https://user-images.githubusercontent.com/49177682/179555924-64d7303e-a5bf-49d2-ad50-f6c1ff5d0c57.png)

**Comment by bzha5848** [comment]
还有就是当我使用推荐的command 我遇到如下问题：
![image](https://user-images.githubusercontent.com/49177682/178429272-e1d09b20-a332-43b9-9964-f1f9024211d5.png)

**Comment by positive666** [comment]
> 你好！
> 
> 我在修改的时候遇到如下问题，请问有什么办法可以解决吗？ ![image](https://user-images.githubusercontent.com/49177682/179555924-64d7303e-a5bf-49d2-ad50-f6c1ff5d0c57.png)

这个是你的hyps的训练yaml中 没有给这个字段 你加上就行了
