### ISSUE TITLE
loss.py里这行问题好像挺多的

### ISSUE THREAD

**Issue by wch243294382** [positive666/yolov5_research#58]
` lbox += ((bbox_iou(pbox.T, tbox[i], x1y1x2y2=False)** g2)*(1 - iou)).mean() `
pbox还需要转置吗 还有x1y1x2y2是否要换成xywh，g2前少了self

**Comment by positive666** [comment]
> `lbox += ((bbox_iou(pbox.T, tbox[i], x1y1x2y2=False)** g2)*(1 - iou)).mean()` pbox还需要转置吗 还有x1y1x2y2是否要换成xywh，g2前少了self

嗯 稍等吧 还在抽空更新

**Comment by positive666** [comment]
收到

**Comment by positive666** [comment]
> `lbox += ((bbox_iou(pbox.T, tbox[i], x1y1x2y2=False)** g2)*(1 - iou)).mean()` pbox还需要转置吗 还有x1y1x2y2是否要换成xywh，g2前少了self

已经基本都修复了 v7也在不断更新 感谢你的反馈
