### ISSUE TITLE
如何使用您git里说的deepstream？

### ISSUE THREAD

**Issue by hukaick** [positive666/yolov5_research#6]
## ❔Question

  我需要一个实时的部署要求，按照操作，编译报错了。我调试了很久，希望您能更新添加一下使用说明

**Comment by positive666** [comment]
> ## ❔Question
> 我需要一个实时的部署要求，按照操作，编译报错了。我调试了很久，希望您能更新添加一下使用说明
> 
> ## Additional context

这个程序肯定是没问题的 ，只是还没整理好 并且readme确实旧了 等我更新~
