### ISSUE TITLE
bifpn on yolov5m

### ISSUE THREAD

**Issue by bzha5848** [positive666/yolov5_research#63]
你好！

我先问一下要在yolov5m 上使用 bifpn 的话应该怎么改？

谢谢！！

**Comment by positive666** [comment]
> 你好！
> 
> 我先问一下要在yolov5m 上使用 bifpn 的话应该怎么改？
> 
> 谢谢！！

先看下BIFPN的结构连接 尝试下自己在YAML上去适配，注意每层的tensor维度 去调节

**Comment by positive666** [comment]
> 你好！
> 
> 我先问一下要在yolov5m 上使用 bifpn 的话应该怎么改？
> 
> 谢谢！！

对接好通道数就行了
