### ISSUE TITLE
大佬，用您的代码的解耦头虽然没运行起来，但是运算量从15.8GFLOPs增加到了56.7GFLOPs，这个正常吗

### ISSUE THREAD

**Issue by lulin1995** [positive666/yolov5_research#67]
## ❔Question
大佬，用您的代码的解耦头虽然没运行起来，但是运算量从15.8GFLOPs增加到了56.7GFLOPs，这个正常吗

**Comment by positive666** [comment]
> ## ❔Question
> 大佬，用您的代码的解耦头虽然没运行起来，但是运算量从15.8GFLOPs增加到了56.7GFLOPs，这个正常吗
> 
> ## Additional context

代码一直更新啊 抱歉  因为 V5一直更新 参考他的代码优化合并最新的改动时候 出了些问题  那个是参数量大后面可以重写的
