### ISSUE TITLE
Decoupled_Detect bug

### ISSUE THREAD

**Issue by 2239891257** [positive666/yolov5_research#68]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## To Reproduce (REQUIRED)

Input:
```
import torch

a = torch.tensor([5])
c = a / 0
```

Output:
```
Traceback (most recent call last):
  File "/Users/glennjocher/opt/anaconda3/envs/env1/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-be04c762b799>", line 5, in <module>
    c = a / 0
RuntimeError: ZeroDivisionError
```

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

**Comment by 2239891257** [comment]
File "/root/Yolo_Transformer/models/yolo_test.py", line 203, in forward
    self.grid[i], self.anchor_grid[i] = self._make_grid(nx, ny, i)
RuntimeError: expand(torch.cuda.HalfTensor{[3, 68, 84, 2]}, size=[]): the number of sizes provided (0) must be greater or equal to the number of dimensions in the tensor (4)

**Comment by positive666** [comment]
> File "/root/Yolo_Transformer/models/yolo_test.py", line 203, in forward self.grid[i], self.anchor_grid[i] = self._make_grid(nx, ny, i) RuntimeError: expand(torch.cuda.HalfTensor{[3, 68, 84, 2]}, size=[]): the number of sizes provided (0) must be greater or equal to the number of dimensions in the tensor (4
Hello, please provide the your model structure or run the command

**Comment by positive666** [comment]
> File "/root/Yolo_Transformer/models/yolo_test.py", line 203, in forward self.grid[i], self.anchor_grid[i] = self._make_grid(nx, ny, i) RuntimeError: expand(torch.cuda.HalfTensor{[3, 68, 84, 2]}, size=[]): the number of sizes provided (0) must be greater or equal to the number of dimensions in the tensor (4)

Hello, please provide the model structure  or run the command
