### ISSUE TITLE
GAM训练问题

### ISSUE THREAD

**Issue by xing-bing** [positive666/yolov5_research#69]
## ❔Question
你好，请问一下我在网络中加入GAM注意力机制之后使用yolos可以正常训练，但是要是使用大一点的模型比如yolom的话训练时就会出现Nan

**Comment by positive666** [comment]
> ## ❔Question
> 你好，请问一下我在网络中加入GAM注意力机制之后使用yolos可以正常训练，但是要是使用大一点的模型比如yolom的话训练时就会出现Nan
> 
> ## Additional context

你是自己加的配置的YAML吗？

**Comment by wch243294382** [comment]
> 请

请问是新版的原因吗 我用几个月前的版本的yaml没事，今天下的新版，把yaml直接拿过来 其中包含gam 损失直接就nan了

**Comment by positive666** [comment]
> ## ❔Question
> 你好，请问一下我在网络中加入GAM注意力机制之后使用yolos可以正常训练，但是要是使用大一点的模型比如yolom的话训练时就会出现Nan
> 
> ## Additional context

这个不是模型的问题 是我合并V7的数据增强的问题 已经修复了 有问题随时联系

**Comment by positive666** [comment]
> ## ❔Question
> 你好，请问一下我在网络中加入GAM注意力机制之后使用yolos可以正常训练，但是要是使用大一点的模型比如yolom的话训练时就会出现Nan
> 
> ## Additional context

需要调整下超参
