### ISSUE TITLE
Improvement of the training section

### ISSUE THREAD

**Issue by petter-Wang** [positive666/yolov5_research#7]
## ❔Question
您好，之前跟您在博客上沟通过，看到您开了ISSUE，我按照您的改进思路，想在LOSS和标签匹配上做一下改进，但是我现在没有什么思路，您能再分享下或者一些改进这部分代码上的工作吗？

**Comment by positive666** [comment]
> ## ❔Question
> 您好，之前跟您在博客上沟通过，看到您开了ISSUE，我按照您的改进思路，想在LOSS和标签匹配上做一下改进，但是我现在没有什么思路，您能再分享下或者一些改进这部分代码上的工作吗？
> 
> ## Additional context

这部分工作我也没做  你可以参考下SIMOTA 目前的方法还是以IOU的基准来定义，LOSS的话我做个实验在更新把  网上有很多 Focal的变体 之前那个EIOULOSS 属实是反向优化了

**Comment by petter-Wang** [comment]
> > ## ❔Question
> > 您好，之前跟您在博客上沟通过，看到您开了ISSUE，我按照您的改进思路，想在LOSS和标签匹配上做一下改进，但是我现在没有什么思路，您能再分享下或者一些改进这部分代码上的工作吗？
> > ## Additional context
> 
> 这部分工作我也没做 你可以参考下SIMOTA 目前的方法还是以IOU的基准来定义，LOSS的话我做个实验在更新把 网上有很多 Focal的变体 之前那个EIOULOSS 属实是反向优化了

感谢回答 后续还请多多指教  大佬C++ 强啊学习了
