### ISSUE TITLE
Improvement of yolov5-ASFF

### ISSUE THREAD

**Issue by bzha5848** [positive666/yolov5_research#70]
你好，
我最近在做有关于yolov5-asff的相关网络，我看见 这样一篇文章https://www.mdpi.com/2072-4292/14/14/3498/htm
说应该在ASFF后面加上RFB，我想问一下这个有可能在现在的ASFF里面加上去吗？或者有和RFB类似的东西可以提高ASFF吗？谢谢！！
https://github.com/GOATmessi7/RFBNet/blob/0f1d836df9f90e26422c19732088d76bbd8dd489/models/RFB_Net_mobile.py#L89

**Comment by positive666** [comment]
> 

你好 不过不建议使用ASFF  现在的SOTA Trick要是做研究的话 偏向于标签匹配和模型压缩    至于ASFF我确实不太清楚  因为检测BASE做的比较泛滥了 你可以试试 你的想法  早前有人用过了 效果好像不明显
