### ISSUE TITLE
今天重新下了一个，训练几十个iter loss就nan了

### ISSUE THREAD

**Issue by wch243294382** [positive666/yolov5_research#72]
## ❔Question
请问可能是啥原因

## Additional context
yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了

**Comment by positive666** [comment]
> ## ❔Question
> 请问可能是啥原因
> 
> ## Additional context
> yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了

最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下

**Comment by wch243294382** [comment]
> > ## ❔Question
> > 请问可能是啥原因
> > ## Additional context
> > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> 
> 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下

之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样

**Comment by positive666** [comment]
> > > ## ❔Question
> > > 请问可能是啥原因
> > > ## Additional context
> > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > 
> > 
> > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> 
> 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样

应该修复了 现在

**Comment by wch243294382** [comment]
> > > > ## ❔Question
> > > > 请问可能是啥原因
> > > > ## Additional context
> > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > 
> > > 
> > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > 
> > 
> > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> 
> 应该修复了 现在

我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0

**Comment by positive666** [comment]
> > > > > ## ❔Question
> > > > > 请问可能是啥原因
> > > > > ## Additional context
> > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > 
> > > > 
> > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > 
> > > 
> > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > 
> > 
> > 应该修复了 现在
> 
> 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0

是V7的cfg吗

**Comment by wch243294382** [comment]
> > > > > > ## ❔Question
> > > > > > 请问可能是啥原因
> > > > > > ## Additional context
> > > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > > 
> > > > > 
> > > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > > 
> > > > 
> > > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > > 
> > > 
> > > 应该修复了 现在
> > 
> > 
> > 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0
> 
> 是V7的cfg吗

都用的v5的

**Comment by positive666** [comment]
> > > > > > > ## ❔Question
> > > > > > > 请问可能是啥原因
> > > > > > > ## Additional context
> > > > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > > > 
> > > > > > 
> > > > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > > > 
> > > > > 
> > > > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > > > 
> > > > 
> > > > 应该修复了 现在
> > > 
> > > 
> > > 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0
> > 
> > 
> > 是V7的cfg吗
> 
> 都用的v5的

哪个yaml 运行命令贴一下

**Comment by wch243294382** [comment]
> > > > > > > ## ❔Question
> > > > > > > 请问可能是啥原因
> > > > > > > ## Additional context
> > > > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > > > 
> > > > > > 
> > > > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > > > 
> > > > > 
> > > > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > > > 
> > > > 
> > > > 应该修复了 现在
> > > 
> > > 
> > > 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0
> > 
> > 
> > 是V7的cfg吗
> 
> 都用的v5的



> > > > > > ## ❔Question
> > > > > > 请问可能是啥原因
> > > > > > ## Additional context
> > > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > > 
> > > > > 
> > > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > > 
> > > > 
> > > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > > 
> > > 
> > > 应该修复了 现在
> > 
> > 
> > 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0
> 
> 是V7的cfg吗

刚试了下v5官方的代码，从5s到5s+carafe 中间隔了10分钟，mosaic结果一致

**Comment by wch243294382** [comment]
> > > > > > > > > ## ❔Question
> > > > > > > > > 请问可能是啥原因
> > > > > > > > > ## Additional context
> > > > > > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > > > > > 
> > > > > > > 
> > > > > > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > > > > > 
> > > > > > 
> > > > > > 应该修复了 现在
> > > > > 
> > > > > 
> > > > > 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0
> > > > 
> > > > 
> > > > 是V7的cfg吗
> > > 
> > > 
> > > 都用的v5的
> > 
> > 
> > > > > > > > ## ❔Question
> > > > > > > > 请问可能是啥原因
> > > > > > > > ## Additional context
> > > > > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > > > > 
> > > > > > > 
> > > > > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > > > > 
> > > > > > 
> > > > > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > > > > 
> > > > > 
> > > > > 应该修复了 现在
> > > > 
> > > > 
> > > > 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0
> > > 
> > > 
> > > 是V7的cfg吗
> > 
> > 
> > 刚试了下v5官方的代码，从5s到5s+carafe 中间隔了10分钟，mosaic结果一致
> 
> 刚又更新了一下推理代码的BUG，因为V5代码更新频率太高了 基本上异常问题都是我合并他的改动导致的 不过他的代码优化更新比V7强了一个档次 你那边现在具体是什么问题呢？

就是不同训练mosaic结果不同，导致精度能差4个点，一次63%一次67%

**Comment by positive666** [comment]
> > > > > > > > > > ## ❔Question
> > > > > > > > > > 请问可能是啥原因
> > > > > > > > > > ## Additional context
> > > > > > > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > > > > > > 
> > > > > > > 
> > > > > > > 应该修复了 现在
> > > > > > 
> > > > > > 
> > > > > > 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0
> > > > > 
> > > > > 
> > > > > 是V7的cfg吗
> > > > 
> > > > 
> > > > 都用的v5的
> > > 
> > > 
> > > > > > > > > ## ❔Question
> > > > > > > > > 请问可能是啥原因
> > > > > > > > > ## Additional context
> > > > > > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > > > > > 
> > > > > > > 
> > > > > > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > > > > > 
> > > > > > 
> > > > > > 应该修复了 现在
> > > > > 
> > > > > 
> > > > > 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0
> > > > 
> > > > 
> > > > 是V7的cfg吗
> > > 
> > > 
> > > 刚试了下v5官方的代码，从5s到5s+carafe 中间隔了10分钟，mosaic结果一致
> > 
> > 
> > 刚又更新了一下推理代码的BUG，因为V5代码更新频率太高了 基本上异常问题都是我合并他的改动导致的 不过他的代码优化更新比V7强了一个档次 你那边现在具体是什么问题呢？
> 
> 就是不同训练mosaic结果不同，导致精度能差4个点，一次63%一次67%

现在同样结构和官方的V5能对齐吗

**Comment by wch243294382** [comment]
> > > > > > > > > > > ## ❔Question
> > > > > > > > > > > 请问可能是啥原因
> > > > > > > > > > > ## Additional context
> > > > > > > > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 应该修复了 现在
> > > > > > > 
> > > > > > > 
> > > > > > > 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0
> > > > > > 
> > > > > > 
> > > > > > 是V7的cfg吗
> > > > > 
> > > > > 
> > > > > 都用的v5的
> > > > 
> > > > 
> > > > > > > > > > ## ❔Question
> > > > > > > > > > 请问可能是啥原因
> > > > > > > > > > ## Additional context
> > > > > > > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > > > > > > 
> > > > > > > 
> > > > > > > 应该修复了 现在
> > > > > > 
> > > > > > 
> > > > > > 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0
> > > > > 
> > > > > 
> > > > > 是V7的cfg吗
> > > > 
> > > > 
> > > > 刚试了下v5官方的代码，从5s到5s+carafe 中间隔了10分钟，mosaic结果一致
> > > 
> > > 
> > > 刚又更新了一下推理代码的BUG，因为V5代码更新频率太高了 基本上异常问题都是我合并他的改动导致的 不过他的代码优化更新比V7强了一个档次 你那边现在具体是什么问题呢？
> > 
> > 
> > 就是不同训练mosaic结果不同，导致精度能差4个点，一次63%一次67%
> 
> 现在同样结构和官方的V5能对齐吗

我跑下看看结果， 还有gam注意力机制我看你在yolo.py那里没添加，看别人是加上的，请问这两者有区别吗

**Comment by positive666** [comment]
> > > > > > > > > > > > ## ❔Question
> > > > > > > > > > > > 请问可能是啥原因
> > > > > > > > > > > > ## Additional context
> > > > > > > > > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 应该修复了 现在
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0
> > > > > > > 
> > > > > > > 
> > > > > > > 是V7的cfg吗
> > > > > > 
> > > > > > 
> > > > > > 都用的v5的
> > > > > 
> > > > > 
> > > > > > > > > > > ## ❔Question
> > > > > > > > > > > 请问可能是啥原因
> > > > > > > > > > > ## Additional context
> > > > > > > > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 应该修复了 现在
> > > > > > > 
> > > > > > > 
> > > > > > > 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0
> > > > > > 
> > > > > > 
> > > > > > 是V7的cfg吗
> > > > > 
> > > > > 
> > > > > 刚试了下v5官方的代码，从5s到5s+carafe 中间隔了10分钟，mosaic结果一致
> > > > 
> > > > 
> > > > 刚又更新了一下推理代码的BUG，因为V5代码更新频率太高了 基本上异常问题都是我合并他的改动导致的 不过他的代码优化更新比V7强了一个档次 你那边现在具体是什么问题呢？
> > > 
> > > 
> > > 就是不同训练mosaic结果不同，导致精度能差4个点，一次63%一次67%
> > 
> > 
> > 现在同样结构和官方的V5能对齐吗
> 
> 我跑下看看结果， 还有gam注意力机制我看你在yolo.py那里没添加，看别人是加上的，请问这两者有区别吗

你说的是YAML的注册吧？  本质无区别的

**Comment by wch243294382** [comment]
> > > > > > > > > > > > > ## ❔Question
> > > > > > > > > > > > > 请问可能是啥原因
> > > > > > > > > > > > > ## Additional context
> > > > > > > > > > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 应该修复了 现在
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 是V7的cfg吗
> > > > > > > 
> > > > > > > 
> > > > > > > 都用的v5的
> > > > > > 
> > > > > > 
> > > > > > > > > > > > ## ❔Question
> > > > > > > > > > > > 请问可能是啥原因
> > > > > > > > > > > > ## Additional context
> > > > > > > > > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 应该修复了 现在
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0
> > > > > > > 
> > > > > > > 
> > > > > > > 是V7的cfg吗
> > > > > > 
> > > > > > 
> > > > > > 刚试了下v5官方的代码，从5s到5s+carafe 中间隔了10分钟，mosaic结果一致
> > > > > 
> > > > > 
> > > > > 刚又更新了一下推理代码的BUG，因为V5代码更新频率太高了 基本上异常问题都是我合并他的改动导致的 不过他的代码优化更新比V7强了一个档次 你那边现在具体是什么问题呢？
> > > > 
> > > > 
> > > > 就是不同训练mosaic结果不同，导致精度能差4个点，一次63%一次67%
> > > 
> > > 
> > > 现在同样结构和官方的V5能对齐吗
> > 
> > 
> > 我跑下看看结果， 还有gam注意力机制我看你在yolo.py那里没添加，看别人是加上的，请问这两者有区别吗
> 
> 你说的是YAML的注册吧？ 本质无区别的

是那个m in 好多模块，没区别就行，谢谢啦

**Comment by positive666** [comment]
> > > > > > > > > > > > > > ## ❔Question
> > > > > > > > > > > > > > 请问可能是啥原因
> > > > > > > > > > > > > > ## Additional context
> > > > > > > > > > > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 应该修复了 现在
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 是V7的cfg吗
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 都用的v5的
> > > > > > > 
> > > > > > > 
> > > > > > > > > > > > > ## ❔Question
> > > > > > > > > > > > > 请问可能是啥原因
> > > > > > > > > > > > > ## Additional context
> > > > > > > > > > > > > yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > 最近的这版数据增强有问题 目前在修复中 晚上会上传一个修复版的 不过具体我还要在研究下
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 之前那个倒是咋都固定不了mosaic。我看这个版本可以了 每次训练都一样
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 应该修复了 现在
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我看loss没事了，但换了下cfg的yaml后mosaic结果又不一样了。。。用了--seed 0
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 是V7的cfg吗
> > > > > > > 
> > > > > > > 
> > > > > > > 刚试了下v5官方的代码，从5s到5s+carafe 中间隔了10分钟，mosaic结果一致
> > > > > > 
> > > > > > 
> > > > > > 刚又更新了一下推理代码的BUG，因为V5代码更新频率太高了 基本上异常问题都是我合并他的改动导致的 不过他的代码优化更新比V7强了一个档次 你那边现在具体是什么问题呢？
> > > > > 
> > > > > 
> > > > > 就是不同训练mosaic结果不同，导致精度能差4个点，一次63%一次67%
> > > > 
> > > > 
> > > > 现在同样结构和官方的V5能对齐吗
> > > 
> > > 
> > > 我跑下看看结果， 还有gam注意力机制我看你在yolo.py那里没添加，看别人是加上的，请问这两者有区别吗
> > 
> > 
> > 你说的是YAML的注册吧？ 本质无区别的
> 
> 是那个m in 好多模块，没区别就行，谢谢啦

这个和YAML的书写有关系 和计算无关

**Comment by positive666** [comment]
> ## ❔Question
> 请问可能是啥原因
> 
> ## Additional context
> yolov7刚出那个版本我训练没事。今天重新下了一个，训练几十个iter loss就nan了

你有我之前版本的代码的话 应该是学习率参数问题 你对比下
