### ISSUE TITLE
Decoupled_Detect 添加的bug

### ISSUE THREAD

**Issue by qiao-xu** [positive666/yolov5_research#73]
## ❔Question
训练会自动下载yolov5n.pt，即使我指定的是yolov5s，
增加解耦头flops直接到56，打印模型同时还会打印出一堆tensor

**Comment by positive666** [comment]
> ## ❔Question
> 训练会自动下载yolov5n.pt，即使我指定的是yolov5s， 增加解耦头flops直接到56，打印模型同时还会打印出一堆tensor
> 
> ## Additional context

LOG问题删了  你说的YOLOV5N.PT下载我没复现过

**Comment by positive666** [comment]
> ## ❔Question
> 训练会自动下载yolov5n.pt，即使我指定的是yolov5s， 增加解耦头flops直接到56，打印模型同时还会打印出一堆tensor
> 
> ## Additional context

是昨天更新的代码吗？

**Comment by positive666** [comment]
> ## ❔Question
> 训练会自动下载yolov5n.pt，即使我指定的是yolov5s， 增加解耦头flops直接到56，打印模型同时还会打印出一堆tensor
> 
> ## Additional context

我看到自动下载了 我看下今天下午没事的话 我会修复

**Comment by positive666** [comment]
> ## ❔Question
> 训练会自动下载yolov5n.pt，即使我指定的是yolov5s， 增加解耦头flops直接到56，打印模型同时还会打印出一堆tensor
> 
> ## Additional context

LOG打印我删除了；自动下载不是BUG是V5官方的check，去测试混合精度功能，所以会调用yolov5n的模型自动下载 然后去推理比对FP32的普通输出是否一致，这是一个检验功能 你可以关闭 N的大小其实应该对你的存储没什么影响

**Comment by qiao-xu** [comment]
> ## ❔Question
> 训练会自动下载yolov5n.pt，即使我指定的是yolov5s， 增加解耦头flops直接到56，打印模型同时还会打印出一堆tensor
> 
> ## Additional context
