### ISSUE TITLE
我想问下  大佬您的解耦头初始化时根据什么写的

### ISSUE THREAD

**Issue by 13604828410** [positive666/yolov5_research#77]
这是我根据yolov6写的初始化  不知道为啥和v5不一样，求指点
![image](https://user-images.githubusercontent.com/51470903/189736130-b05b368c-f6f3-456b-8fa2-65d3577f03fb.png)

**Comment by positive666** [comment]
目前版本是用了V5作者的，之前那版初始化被我overwrite了。这个没什么特别的  具体写法代码是根据你解耦头的类结构定义的代码  就是分类和回归分开就行，你这个V6就是这个写法啊很明确
