### ISSUE TITLE
您好 我怕想问下，如果我想开启QFocalLoss或者FocalLoss，这个地方我改成sum还是mean还是none，

### ISSUE THREAD

**Issue by FYM1209** [positive666/yolov5_research#78]
## ❔Question
您好 我怕想问下，如果我想开启QFocalLoss或者FocalLoss，这个reduction我改成sum还是mean还是none？谢谢

## Additional context
![image](https://user-images.githubusercontent.com/93715148/200107443-2b3cd28d-e6b5-4ed6-b9c1-c60ebfd3e1dc.png)

**Comment by positive666** [comment]
> ## ❔Question
> 您好 我怕想问下，如果我想开启QFocalLoss或者FocalLoss，这个reduction我改成sum还是mean还是none？谢谢
> 
> ## Additional context
> ![image](https://user-images.githubusercontent.com/93715148/200107443-2b3cd28d-e6b5-4ed6-b9c1-c60ebfd3e1dc.png)

你好，reduction默认是MEAN（输出和/迭代次数）的，你不需要特意设置的
