### ISSUE TITLE
有关yolov7 pose训练问题

### ISSUE THREAD

**Issue by tonyskypc** [positive666/yolov5_research#79]
请问作者是否亲自在最新的代码上跑过yolov7 pose训练？出现了多个错误呢？

**Comment by positive666** [comment]
> 请问作者是否亲自在最新的代码上跑过yolov7 pose训练？出现了多个错误呢？

哪里有问题 可以贴出来 报错

**Comment by tonyskypc** [comment]
已经解决过了，谢谢。
