### ISSUE TITLE
yolov7-pose训练回归关键点只有15个

### ISSUE THREAD

**Issue by tonyskypc** [positive666/yolov5_research#81]
## ❔Question
https://github.com/WongKinYiu/yolov7/tree/pose 基于这个代码，使用coco2017训练，头部的关键点会超出范围，使用您的代码训练，头部的关键点缺少2个，跟踪发现是关键点y为0，被过滤了。
请教怎么可以做到17个关键点都回归准确，谢谢。

## Additional context
![a](https://user-images.githubusercontent.com/58210597/202608269-c9b12f47-5c92-403c-a452-8784993cd51c.jpg)
基于wongkingyiu代码
![aa](https://user-images.githubusercontent.com/58210597/202608317-374edd15-23eb-445a-8960-dbd5a4046bb1.jpg)
基于您的pose代码

**Comment by positive666** [comment]
> ## ❔Question
> https://github.com/WongKinYiu/yolov7/tree/pose 基于这个代码，使用coco2017训练，头部的关键点会超出范围，使用您的代码训练，头部的关键点缺少2个，跟踪发现是关键点y为0，被过滤了。 请教怎么可以做到17个关键点都回归准确，谢谢。
> 
> ## Additional context
> ![a](https://user-images.githubusercontent.com/58210597/202608269-c9b12f47-5c92-403c-a452-8784993cd51c.jpg) 基于wongkingyiu代码 ![aa](https://user-images.githubusercontent.com/58210597/202608317-374edd15-23eb-445a-8960-dbd5a4046bb1.jpg) 基于您的pose代码

收到你的问题 ！我会抽空检查解决好

**Comment by positive666** [comment]
> ## ❔Question
> https://github.com/WongKinYiu/yolov7/tree/pose 基于这个代码，使用coco2017训练，头部的关键点会超出范围，使用您的代码训练，头部的关键点缺少2个，跟踪发现是关键点y为0，被过滤了。 请教怎么可以做到17个关键点都回归准确，谢谢。
> 
> ## Additional context
> ![a](https://user-images.githubusercontent.com/58210597/202608269-c9b12f47-5c92-403c-a452-8784993cd51c.jpg) 基于wongkingyiu代码 ![aa](https://user-images.githubusercontent.com/58210597/202608317-374edd15-23eb-445a-8960-dbd5a4046bb1.jpg) 基于您的pose代码

这个问题可能是LOSS问题 我今天晚上有时间 我修复一版本 你可以试试 年底了业务比较忙  效率不会太高

**Comment by positive666** [comment]
https://github.com/TexasInstruments/edgeai-yolov5/pull/48/files    ，
![image](https://user-images.githubusercontent.com/28972473/203754948-082c6554-fba2-4dfb-bf49-28787fe62d0c.png)

**Comment by xinsuinizhuan** [comment]
> > ## ❔Question
> > https://github.com/WongKinYiu/yolov7/tree/pose 基于这个代码，使用coco2017训练，头部的关键点会超出范围，使用您的代码训练，头部的关键点缺少2个，跟踪发现是关键点y为0，被过滤了。 请教怎么可以做到17个关键点都回归准确，谢谢。
> > ## Additional context
> > ![a](https://user-images.githubusercontent.com/58210597/202608269-c9b12f47-5c92-403c-a452-8784993cd51c.jpg) 基于wongkingyiu代码 ![aa](https://user-images.githubusercontent.com/58210597/202608317-374edd15-23eb-445a-8960-dbd5a4046bb1.jpg) 基于您的pose代码
> 
> 这个问题可能是LOSS问题 我今天晚上有时间 我修复一版本 你可以试试 年底了业务比较忙 效率不会太高

wongkingyiu这个是哪个？有链接吗？
