### ISSUE TITLE
involution

### ISSUE THREAD

**Issue by Posty2030** [positive666/yolov5_research#82]
## Additional context
![1668952416590](https://user-images.githubusercontent.com/89211427/202905992-6e7c2668-ddb6-4115-9564-2bdce55faa93.jpg)

**Comment by positive666** [comment]
> ## ❔Question 增加了involution层后，head中的concat为什么要拼接involution层而不是C3层呢
> ## Additional context
> ![1668952416590](https://user-images.githubusercontent.com/89211427/202905992-6e7c2668-ddb6-4115-9564-2bdce55faa93.jpg)

很高兴收到你的问题，这个YAML 是去年旧的一个例子  没有定式做法，你可以自由修改  因为这个论文的作者LIDUO当时抄袭被曝光了 并且直接使用也有问题 不建议看这个了 最重要的是你已经熟悉了修改方式 因为我去年已经停止了只取修改网络结构的方式，我建议可以尝试比如递归门控制卷积或者selfa-attention 最近比较新的试试

**Comment by positive666** [comment]
> 
很高兴收到你的问题，这个YAML 是去年旧的一个例子 没有定式做法，你可以自由修改 因为这个论文的作者LIDUO当时抄袭被曝光了 并且直接使用也有问题 不建议看这个了 最重要的是你已经熟悉了修改方式 因为我去年已经停止了只修改网络结构的方式，后面有work的会纳入代码中，我建议可以尝试比如递归门控制卷积或者selfa-attention 最近比较新的试试

**Comment by Posty2030** [comment]
好的，谢谢
