### ISSUE TITLE
你好,请问你的数据集真能跑通吗?同样的YOLOV5s,我用一模一样的数据集跑甚至无法收敛

### ISSUE THREAD

**Issue by zmdcs** [positive666/yolov5_research#84]
## ❔Question
YOLOv5s无法收敛,甚至第一代就nan

**Comment by positive666** [comment]
> ## ❔Question
> YOLOv5s无法收敛,甚至第一代就nan
> 
> ## Additional context

你好 可以发来具体问题信息 是我的问题 我会修复

**Comment by positive666** [comment]
> > ## ❔Question
> > YOLOv5s无法收敛,甚至第一代就nan
> > ## Additional context
> 
> 你好 可能是更新的问题   我会尽快检查下

**Comment by hukaick** [comment]
> ## ❔Question
> YOLOv5s无法收敛,甚至第一代就nan
> 
> ## Additional context

我这边没问题 不过你说的这个我前几个月遇到过 是作者更新太频繁了有些BUG 后来他修复了你需要用最新的代码 然后有问题提一下  我跟他这个项目自己改实验两年了

**Comment by positive666** [comment]
> ## ❔Question
> YOLOv5s无法收敛,甚至第一代就nan
> 
> ## Additional context

确实是我更新引发了BUG  修复好会通知

**Comment by positive666** [comment]
> ## ❔Question
> YOLOv5s无法收敛,甚至第一代就nan
> 
> ## Additional context

我检查了下 确实是更新引发了BUG我会尽快修复 感谢你的及时反馈
