### ISSUE TITLE
123

### ISSUE THREAD

**Issue by thi23459112** [positive666/yolov5_research#97]
謝謝

**Comment by positive666** [comment]
可以的 兼容了V8 V8怎么用这个就怎么用 ，只是目前项目训练代码有问题，我这边有些NLP的工作 ，过后我会重构。可以直接使用V8的结构自带bytetrack 集成 ，ROI和COUNT你自己加也可以

**Comment by geoxpert0001** [comment]
ROI 跟count 對於小白我比較不熟 想說你是否能直接新增一個
